logType: formatted
storeType: sqlite
queryLocation: "/Users/ravianthapu/Downloads/testlog/"
fileFilter: ^query.*\.log.*$
#fileFilter: .*\.json$
#fileFilter: .*\.zip
#fileType: zip
#zipFileNameFilter: .\/query.*\.log.*$
databaseURI: jdbc:sqlite:query_db.db
defaultRuntime: pipelined
#annotationProcessingEnabled: true
#annotaionStorageConfig: sqlite_graphql_v1.yaml
#annotationRecordType: map